### ISSUE TITLE
ImportError: cannot import name tf_logging

### ISSUE THREAD

**Issue by qinghua2016** [plowman/python-mcparseface#1]
I can successfuly run " bazel test --local_resources 2048,.5,1.0 --genrule_strategy=standalone syntaxnet/... util/utf8/..." with 17 tests pass. Also I succeed to run "echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh". But when I run the command "python pyparseface.py   "in terminal, it print as "I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "pyparseface.py", line 19, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name tf_logging
"
it is actually that the python code also failed to do operations as follows:
 "from syntaxnet import sentence_pb2, structured_graph_builder
from syntaxnet.ops import gen_parser_ops"
Do you know why?

**Comment by plowman** [comment]
Hey @qinghua2016 thanks for filing a bug!

I made a change earlier today that might fix this issue. Can you pull the latest code and try again?

**Comment by qinghua2016** [comment]
Do you mean change the projct root from "PROJECT_ROOT = os.getcwd()" to "
 +PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))" ? I have tried it but it still has the same   
error as I have attached above. I copy tf_logging.py to the dir of pyparseface, it succeed to import tf_logging . But it occure the error ad follows:
File "/home/qinghua/syntaxnet_model/pyparseface.py", line 20, in <module>
    from syntaxnet import sentence_pb2, structured_graph_builder
ImportError: No module named syntaxnet
I find that sentence_pb2.py is in the path of 'models/syntaxnet/bazel-bin/syntaxnet/ parser_eval.runfiles/__main__/syntaxnet/. Therefore, I change the runfiles_path to be "runfiles_path = os.path.join(PROJECT_ROOT, 'models', 'syntaxnet', 'bazel-bin', 'syntaxnet', 'parser_eval.runfiles')", then it prints as follows:
/usr/bin/python2.7 /home/qinghua/syntaxnet_model/pyparseface.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: .:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Process finished with exit code 1.
 Do you know why? Hope for you answering.

**Comment by qinghua2016** [comment]
One more question, I installed tensorflow earlier, do I need to remove the tensorflow so that to use the models' one ?

**Comment by qinghua2016** [comment]
I have successfully run your code. As the provider says, the models of syntaxnet can only work with the  tensorfow in the models. The reason why I failed to run it is that I installed tensorflow before. After I remove tensorfolw, I can run it. But I need to use tensorflow for other things, I am wondering if you have any idea to use pip installed tensorflow for syntaxnet?
