### ISSUE TITLE
Print syntax

### ISSUE THREAD

**Issue by gbolcer** [plowman/python-mcparseface#5]
>>> import pyparseface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hbase/Insync/git/models/syntaxnet/pyparseface.py", line 254
    print tr(input_dict)
           ^
SyntaxError: invalid syntax
>>>

**Comment by DAGG3R09** [comment]
add parenthesis to the print function.
print (tr (input_dict))
